### ISSUE TITLE
Feature: argument wildcards

### ISSUE THREAD

**Issue by bennyhat** [mdurban/rspec-bash#21]
As a shell expectations user I would like to be able to mock output and exit codes with argument wildcards (rspec wildcards of the style, _anything_)

Ex.

```
stubbed_git_command.with_args('pull', anything, '--rebase').outputs('did it')
```

It would be also nice for expectations to allow this too:

Ex.

```
expect(stubbed_git_command).to be_called_with_arguments('pull',anything,'--rebase')
```

**Comment by mdurban** [comment]
220187fe03852332995ff078748e89b223a0a5b6 covers the second part of this issue

**Comment by mdurban** [comment]
https://github.com/mdurban/rspec-bash/pull/62 covers the first part of this issue
