### ISSUE TITLE
Feature :) Make it be_called_with_arguments returns actual differences

### ISSUE THREAD

**Issue by bennyhat** [mdurban/rspec-bash#39]

**Comment by mdurban** [comment]
Bugfix? I think what we have is a feature. The lack of detailed output makes you really have to understand exactly what your script is doing. 🐼

**Comment by bennyhat** [comment]
Noted and updated.

**Comment by mdurban** [comment]
I just saw you changed this to a feature. I was totally kidding about it being a feature and not a bugfix...
