### ISSUE TITLE
Handle the case of no stubbed_commands

### ISSUE THREAD

**Issue by mtromp** [mdurban/rspec-bash#44]
The following fails with "Cannot find /tmp/asdfasdfasdf/*_overrides.sh" because there are no stubbed commands. It works if there are no parameters and/or if any stub is created, regardless of if it's used.

Script under test:
```bash
exit 0
```

Spec:
```ruby
describe 'failing' do
  let(:stubbed_env) {created_stubbed_env}
  it 'will fail' do
    # Add this to see it pass
    # stubbed_env.stub_command(:anything)

    out, err, rv = stubbed_env.execute("path/to/script some_parameter")

    expect(out).to eql ""
    expect(err).to eql ""
    expect(rv.exitstatus).to eql 0
  end 
end
```

**Comment by bennyhat** [comment]
I'm taking a look. This should be easy, especially since there is an integration test for it already ;)
