### ISSUE TITLE
Cannot mock absolute paths

### ISSUE THREAD

**Issue by mtromp** [mdurban/rspec-bash#46]
When requiring mocking of a command that requires a fullpath, the testing fails.

Script:
```bash
${JAVA_HOME}/bin/jps
```

Spec:
```ruby
  let!(:jps_mock) { stubbed_env.stub_command("${JAVA_HOME}/bin/jps") }
```

**Comment by mdurban** [comment]
Fixed by https://github.com/mdurban/rspec-bash/pull/62
