### ISSUE TITLE
#stub_command unable to mock fully qualified paths

### ISSUE THREAD

**Issue by jhoblitt** [mdurban/rspec-bash#67]
Bash allows function names to contain slashes. Eg., `/usr/bin/true() { echo hi; }`  This is useful for mocking out fully qualified commands.

`#stub_command` can not mock out command names that include slashes as it breaks the tmpfile path construction.  Eg.:

     Errno::ENOENT:
       No such file or directory @ rb_sysopen - /tmp/d20170915-28365-4mrhkj/usr/bin/true_overrides.sh

**Comment by bbrewerpillar** [comment]
Hey, Josh. Thanks for adding this. It's kind of good timing, as Mike just threw away his first attempt at making those work.

The solution you propose is exactly how we plan on making that work. I'll give it a shot this weekend and keep you in the loop.

**Comment by mdurban** [comment]
This fix in, so it should be good to go with the next release. We have few other things to bundle in but the release should be soon.
